// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ObservationController from "./observation_controller"
application.register("observation", ObservationController)

import PointageController from "./pointage_controller"
application.register("pointage", PointageController)

import SweetalertController from "./sweetalert_controller"
application.register("sweetalert", SweetalertController)
